### ISSUE TITLE
Error in browser.py

### ISSUE THREAD

**Issue by credo99** [plysytsya/EbookTranslator#1]
Hi, thanks for the project is extremely useful. It would be great if you could post a few lines about the usage commands. I figured out from the ebook_translator.py there is a way to eidt the last block in order to change the language and file parameters for what I need but ran into these problems:

Reading text into memory.
Tokenizing text into sentences.
Starting translation from the beginning.
Initializing DeepL translator
Traceback (most recent call last):
  File "./scripts/ebook_translator.py", line 64, in <module>
    ebook_translator = EbookTranslator(path, "de", "en", engine="DeepL")
  File "./scripts/ebook_translator.py", line 17, in __init__
    self.translator = Translator(source_language, target_language, engine)
  File "C:\Users\Netadmin\Documents\GitHub\EbookTranslator\scripts\translator.py", line 14, in __init__
    self.set_engine(engine)
  File "C:\Users\Netadmin\Documents\GitHub\EbookTranslator\scripts\translator.py", line 22, in set_engine
    self.engine = DeepLEngine(self.source_language, self.target_language)
  File "C:\Users\Netadmin\Documents\GitHub\EbookTranslator\scripts\translator.py", line 58, in __init__
    self.browser = Browser(headless=True)
  File "C:\Users\Netadmin\Documents\GitHub\EbookTranslator\scripts\browser.py", line 38, in __init__
    self.start()
  File "C:\Users\Netadmin\Documents\GitHub\EbookTranslator\scripts\browser.py", line 41, in start
    chrome_binary = self.choose_browser_binary()[0]
TypeError: 'NoneType' object is not subscriptable

Do you know why?

Thanks,

Radu

**Comment by plysytsya** [comment]
Looks like you don't have a proper selenium setup. You need the chrome or geckodriver (firefox) from seleniumhq.org
Then put the binary-file (chromedriver, or geckodriver) into a directory called "webdrivers" under scripts, i.e. /scripts/webdrivers/chromedriver

**Comment by plysytsya** [comment]
You can also temporarily set headless to False to see if the browser starts up properly.

**Comment by plysytsya** [comment]
I also pushed a wrapper for a google translator on the google cloud platform (it's paid but you can use it for free in the first year). It's in the GCP branch. All in all I started to use the paid thing without paying because the selenium scraper is very slow and hard to maintain.
