### ISSUE TITLE
Error when using Google special chars

### ISSUE THREAD

**Issue by credo99** [plysytsya/EbookTranslator#2]
Hi again, if using a German text with special characters as source language and Google as engine it comes to this error:

Reading text into memory.
Tokenizing text into sentences.
Starting translation from the beginning.
Initializing Google translator
  0%|▋                                                                                                                                                                          | 16/4290 [00:03<17:36,  4.05it/s]
Traceback (most recent call last):
  File "./scripts/ebook_translator.py", line 65, in <module>
    ebook_translator.translate()
  File "./scripts/ebook_translator.py", line 23, in translate
    self.write_to_file(both_sentences, self.out_path)
  File "./scripts/ebook_translator.py", line 42, in write_to_file
    file.write(text)
  File "C:\Radu\Miniconda3\envs\purr2\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 18-19: character maps to <undefined>

**Comment by credo99** [comment]
With google method I fixed the initial error with adding encoding="utf-8" to the write method but still the translation is poor, mixed german and english in the output file, special chars are not properly displayed. I think the Deepl method should work better since it use scrapping but please take my advice if you haven't already, allow for large timeouts between calls since sometimes (like a few hours ago) the deepl.com website had some connection issues and the translation delay after pasting text in the source textframe was significant. Also I think you have taken into account the 5000 chars limit for pasting text to be translated in the source frame. Thanks

**Comment by plysytsya** [comment]
Hi, the poor translation is because it uses a free version of the google translate API. It also fails at a certain point because of a maximum number of requests. So all in all I gave up on this project because the price for the google or AWS translation APIs is ridiculously cheap.
